version: '3'
services:
 ubuntu:
  image: mirchdocker/eyejo:latest
  container_name: eyejo_ubuntu
  ports:
   - 6103:443
  restart: on-failure
  depends_on:
   - database
  working_dir: /root/eyejo/
  volumes:
   - ./eyejo_config.yaml:/root/eyejo/config.yaml
   - ./screen_data:/root/eyejo/plugin/screen_data
  entrypoint: ["sh", "-c", "python3 manage.py initadmin --user admin --password eyejo@666 --email eyejo@admin.com; nginx; supervisord -c ./supervisord.conf; tail -f /var/log/lastlog"]

 worker:
  image: mirchdocker/eyejo:latest
  container_name: eyejo_worker
  restart: on-failure
  working_dir: /root/eyejo/
  volumes:
   - ./eyejo_config.yaml:/root/eyejo/config.yaml
   - ./screen_data:/root/eyejo/plugin/screen_data/
  entrypoint: ["sh", "-c", "celery -A EyeJo.celery:app worker --loglevel=info -c 2 -O fair -f celery.log"]

 redis:
  image: redis:latest
  container_name: eyejo_redis
  command: redis-server --appendonly yes --requirepass eyejoPass
 
 database:
  image: mariadb:10.5
  container_name: eyejo_mariadb
  command: --init-file /init.sql --max_allowed_packet=52428800 --max_connections=1000
  volumes:
   - ./EyeJo.sql:/init.sql
  environment:
   - MYSQL_ROOT_PASSWORD=eyejo@pass
   - MYSQL_DATABASE=EyeJo
 
